### ISSUE TITLE
Could anyone provide tutorial?

### ISSUE THREAD

**Issue by richjr93** [LevPrav999/tinder_clone#3]
Hi,

Will there be anyone who would do a full in-detail tutorial from A-Z on how to use this project and finally run it in the Android Studio?

My personal issue is I am currently stuck with adding Firebase SDK. I don't know what I am supposed to do with the Gradle files and code provided in the Firebase instructions.

Thank you in advance!

**Comment by LevPrav999** [comment]
Hi!

First of all declone repository, then go to firebase console, configure the project via firebase cli (requires node.js installed) or manually. Next, insert your Fcm token into the secret.dart file, which you can get in the firebase console.

You need these services: firestore, storage, auth, messaging.

You can use my database, I didn't unbind it from the project. However, if you want more control over the application, you will have to re-bind the project.

If you have any questions, you can ask me on telegram. The link is in my profile.

**Comment by LevPrav999** [comment]
You need these services: firestore, storage, auth, messaging.

You can use my database, I didn't unbind it from the project. However, if you want more control over the application, you will have to re-bind the project.

**Comment by richjr93** [comment]
Thank you for replying. I am afraid I can't imagine the steps that you're telling. Would you be okay to assist through TeamViewer in about 4 hours from now?

**Comment by LevPrav999** [comment]
Sorry, TeamViewer is blocked in my country, you can message me on telegram: @timofey_prostov , I can help you with every step of the way

**Comment by richjr93** [comment]
I see. Alright, I've texted you on telegram.
